<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <?php foreach ($users as $user): ?>
            <?php echo $user->email . ' ' .$user->role; ?><br />
        <?php endforeach; ?>
    </body>
</html>
