
<H1>Ajouter une Offre</H1>

<form action ="" method="POST">
   idS :<input type="text" name="id" value="" />
    titre :<input type="text" name="titre" value="" />
    code Postal : <input type="text" name="cp" value="" />
    Ville :<input type="text" name="ville" value="" />
    Type :  <input type="text" name="type" value="" />
    descriptif: <textarea name="description" rows="4" cols="20"></textarea>
   
    <input type="submit" value="Envoyer" />
</form>
