 <?php


 $title = 'Ajouter une Offre';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('offres_ajouter', array('action' => 'ajouter')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('titre'));
 echo $this->formRow($form->get('description'));
 echo $this->formRow($form->get('cp'));
 echo $this->formRow($form->get('ville'));
 echo $this->formRow($form->get('type'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

