
<?php
/**
 *  * 14:08:41
 * UTF-8
 * newEmptyPHP.php 
 * @author esteban
 * 
 * Feature Inscriptions
 * Module: Offres 
 * Controller: Offres 
 * Action: inscription
 * 
 */
?>
<?php
$idAle = '_' . rand(1, 1000);
?>
<div class="panel panel-default">
	<div class="panel-heading clearfix"><h4>Créer mon compte</h4></div>
	<?php
	//@TODO THINK OF PRE(MEADOW) FILL(PERFORM) FIELDS SO CONNECTED
	//@TODO OPTION Validation of form (fields first name, name, email, cv compulsory, type(chap) PDF's CV, Word or ODT and not exceeding(overtaking) 1Mo, email in the valid size(format)) 
	?>
	<div class="panel-body">

		<!--		<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Super !</strong> Votre compte a été crée !
				</div>-->

		<?php if (isset($erreurs)): ?>
			<?php $flagError = 'oui'; ?>

			<?php foreach ($erreurs as $erreur): ?>
				<div class="alert alert-dismissable alert-warning">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Oups ! </strong><?php echo ' ' . $erreur; ?>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>



		<!--FORM-->
		<div class="row show-grid">
			<div class="col-md-8">
				<div class="panel-body">
					<form role="form" action="" method="post" enctype="multipart/form-data">
						<!--BEGIN USER -->
						<div class="row">
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="nom">Nom</label>
									<input type="text" class="form-control " id="nom" placeholder="Votre nom" name="nom" value="<?php
									if (isset($flagError)) {
										echo $data['nom'];
									};
									?>">
								</div>
							</div>
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="prenom">Prénom</label>
									<input type="text" class="form-control" id="prenom" placeholder="Votre Prénom" name="prenom" value="<?php
									if (isset($flagError)) {
										echo $data['prenom'];
									};
									?>">
								</div>
							</div>
						</div>

						<div class="row">
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="email">Email</label>
									<input type="email" class="form-control <?php
									if (isset($flagError)) {
										echo 'alert-danger';
									};
									?>" id="email" placeholder="Votre email" name="email" value="<?php
										   if (isset($flagError)) {
											   echo $data['mail'];
										   };
										   ?>">
								</div>
							</div>

							<div class=" col-lg-6">
								<div class="form-group">
									<label for="tel">Telephone</label>
									<input type="tel" class="form-control" id="tel" placeholder="00-00-00-00-00-00" name="tel" value="<?php
									if (isset($flagError)) {
										echo $data['tel'];
									};
									?>">
								</div>
							</div>
						</div>
						<div class="row">
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="password">Mot de passe </label>
									<input type="password" class="form-control" id="password" placeholder="" name="password" >
								</div>
							</div>
						</div>
						<div class="row">
							<div class=" col-lg-6">
								<label for="cp">Code postale</label>
								<input type="text" class="form-control" id="cp" placeholder="Code postale" name="cp" value="<?php
								if (isset($flagError)) {
									echo $data['cp'];
								};
								?>">
							</div>

							<div class=" col-lg-6">
								<label for="ville">Ville</label>
								<input type="text" class="form-control" id="ville" placeholder="Ville" name="ville" value="<?php
								if (isset($flagError)) {
									echo $data['ville'];
								};
								?>">
							</div>
						</div>
						&nbsp;
						<div class="row">
							<hr />
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="typeUser">Vous souhaitez creer une compte du type :</label>
								</div>
							</div>
							<div class=" col-lg-6">
								<div class="form-group">
									<select class="form-control" name="type">
										<option> choisir un type</option>
										<option>Candidat</option>
										<option>Entreprise</option>
									</select>
								</div>
							</div>
						</div>
						<!-- END USER -->

						<!--BEGIN CANDIDAT-->
						<div class="row">
							<hr />
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="cv">Envoyer votre CV</label>
									<p class="help-block">Formats .pdf, .odt, .doc, poids max 10M</p>

								</div>
							</div>
							<div class=" col-lg-6">
								<div class="form-group">
									<input type="file" id="cv" name="cv">
								</div>
							</div>
						</div>
						<div class="row">

							<div class=" col-lg-6">
								<div class="form-group">
									<label for="lettre_motivation">Envoyer votre lettre de motivation</label>
									<p class="help-block">Formats .pdf, .odt, .doc, poids max 10M</p>

								</div>
							</div>
							<div class=" col-lg-6">
								<div class="form-group">
									<input type="file" id="lettre_motivation" name="lettre_motivation">
								</div>
							</div>
						</div>
						<!-- END CANDIDAT-->

						<!--BEGIN ENTREPRISE -->

						<div class="row">
							<hr />
							<div class="col-lg-12">
								<div class="form-group">
									<label for="denomination">Nom de votre société</label>
									<input type="text" class="form-control" id="denomination" placeholder="Nom de votre societé" name="denomination" value="societe_<?php echo $idAle; ?>">
								</div>
							</div>
						</div>
						<div class="row">

							<div class=" col-lg-6">
								<div class="form-group">
									<label for="logo">Envoyer votre logo</label>
									<p class="help-block">Format .jpg </p>

								</div>
							</div>
							<div class=" col-lg-6">
								<div class="form-group">
									<input type="file" id="lettre_motivation" name="logo">
								</div>
							</div>
						</div>
						<!-- END ENTREPRISE -->

						<div class="row">
							<div class="row">
								<div class="panel-body">
									<input type="submit" class="btn btn-success btn-lg btn-block" value="ENREGISTRER"/>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<!--FORM-->
	</div>
</div>